### ISSUE TITLE
Import and Export via JSON

### ISSUE THREAD

**Issue by danhellem** [danhellem/azure-devops-admin-cli#12]

**Comment by lohithgn** [comment]
@danhellem can you put some insights on what the import & export requirements are like?

Export - do you have in mind like a user passes /export:json flag param & if its there the output to be serialized to JSON stored on disk ?

looking for whats needed to code

**Comment by danhellem** [comment]
@lohithgn honestly i have no clue on why i created this issue. I am going to close this issue
