### ISSUE TITLE
Clone work item type from one process to another

### ISSUE THREAD

**Issue by danhellem** [danhellem/azure-devops-admin-cli#13]
Clone from one process to another 
Clone to a new type within the same process

**Comment by Scriptwarrior1027** [comment]
@danhellem  did this ever make it to Production in Azure DevOps?
I tried checking the Azure DevOps CLI documentation and I don't see how to clone Work Item Types.

**Comment by danhellem** [comment]
this CLI is something I put together.. You will need to go on that repo if  you are looking for the official supported CLI
